### ISSUE TITLE
detection box 활성화되는 꼭지점 갯수 수정 요청

### ISSUE THREAD

**Issue by HunJ93** [ROBOTIS-move/labelme#110]
현재 프로그램에서 detection box를 생성하면 꼭지점이 좌상단, 우하단 2개만 생성되고 있습니다.

현재 상태로는 좌하단의 꼭지점만 움직여 수정해도 되는 부분을 두 꼭지점을 모두 움직여야만 수정이 가능하기 때문에 추후 라벨러들의 불편함이 예상됩니다.

모든 꼭지점에서 수정이 가능하도록 해주세요.

**Comment by jongsuff** [comment]
최대한 빠르게 작업 해보겠습니다~!

**Comment by jongsuff** [comment]
요청하신 기능은 #113 작업으로 추가되었습니다!
