### ISSUE TITLE
[segmentation] 이미지 밖으로 나가는 선이 나가는 현상 수정 

### ISSUE THREAD

**Issue by HunJ93** [ROBOTIS-move/labelme#24]
![요청 사항 1](https://user-images.githubusercontent.com/100122356/178670360-46f420ce-ed26-4ecd-95e9-6e04a01a1296.png)

예시 이미지의 양 옆 빨간 동그라미와 같이 완성된 segmentation을 옮기게 되면 이미지 밖으로 선이 밖으로 나가게 됩니다.
라벨러들이 잘못 옮기고 인지하지 못해 이로 인한 수정 요청사항도 대부분을 차지하고 있습니다.

해당 현상 수정 요청드립니다.

**Comment by eungiCho** [comment]
라벨을 클릭 후 이동했을 때의 점 위치를 계산해서 이미지 영역 밖으로 나가게되면 라벨을 이동시키지 않도록 조치했습니다.
