### ISSUE TITLE
방향키 입력 시 박스 이동 픽셀량 개선

### ISSUE THREAD

**Issue by jongsuff** [ROBOTIS-move/labelme#31]
- 현재 방향키 입력 시 박스 이동량이 너무 많은것 같습니다.
- 방향키 입력 시 박스 이동 픽셀을 2픽셀 정도로 수정해 주시면 감사하겠습니다.

**Comment by eungiCho** [comment]
라벨의 move speed를 요청해주신 `2.0`으로 변경했습니다.
