### ISSUE TITLE
error 검출 시 해당 문구 터미널에서 가시성 확보

### ISSUE THREAD

**Issue by HunJ93** [ROBOTIS-move/labelme#34]
![에러](https://user-images.githubusercontent.com/100122356/179895076-bbc831a5-09de-4030-90fd-9ecf5387dc02.png)

위 이미지와 같이 error 파일 발견 시 다른 글씨 때문에 한 눈에 알아보기 힘든 점이 있습니다.
해당 문구 앞 뒤로 가시성을 높여줄 수 있는 기호가 추가되면 좋을 것 같습니다.

아울러, 어떤 Label name이 오류가 났는지도 확인 할 수 있으면 좋을 것 같습니다.

**Comment by eungiCho** [comment]
에러 문구를 빨간색으로 표기할 수 있도록 코드 수정했습니다.
윈도우에서도 잘 동작하는 것 확인했습니다~!
