### ISSUE TITLE
Label name list가 화면 중앙에 위치하지 않는 이슈

### ISSUE THREAD

**Issue by HunJ93** [ROBOTIS-move/labelme#37]
![image (1)](https://user-images.githubusercontent.com/100122356/180360690-458dfaad-0f9c-43f2-931a-5947affe3397.png)
![image](https://user-images.githubusercontent.com/100122356/180360695-741257ed-327a-41d3-8ad2-f2f836cbaa1c.png)

새로운 class를 생성하거나 이름을 편집할 때 label name list 창이 화면 중앙에 위치하지 않고 화면 밖으로 나가는 이슈

**Comment by eungiCho** [comment]
팝업을 labelme 창 안쪽에 띄울 수 있도록 조치하였습니다.
