### ISSUE TITLE
Labelme 사용 이슈 (~5/27)

### ISSUE THREAD

**Issue by eungiCho** [ROBOTIS-move/labelme#4]
- 라벨러분들께서 말씀해주신 `labelme` 사용 중 이슈들을 남겨주세요.
- 발생한 이슈들 중 개선 가능한 부분을 수정하여 `5월 27일`에 업데이트된 버전을 배포하겠습니다.

**Comment by eungiCho** [comment]
- [ ] 변환 프로그램 실행 시 이미지 전체에 하기 이미지와 같은 에러 발생, 이미지 변환에는 문제 없음

![matplot error](https://user-images.githubusercontent.com/58972713/168502926-1e6c93e4-84b5-4092-bba5-d059842f44ca.png)

**Comment by eungiCho** [comment]
- [ ] 라벨링을 진행할 때 마우스 커서를 움직이면 커서 모양이 계속 바뀜(일반커서, 십자커서),
라벨링 진행에는 문제가 없지만 시각적으로 불편함을 느낌


https://user-images.githubusercontent.com/58972713/168503975-ad8346b1-4bec-4ae7-90c1-aa92c751749f.mp4

**Comment by eungiCho** [comment]
- [ ] 라벨링 진행 시 라벨별로 색상 구분되어 polygon에 표기되는 색상 고정 필요, 작업마다 class별 색깔이 바뀌어 연속작업 시 헷갈림

**Comment by HunJ93** [comment]
완성 Polygons에 point추가 기능이 사라져 Polygons수정시 불편함이 있음

**Comment by eungiCho** [comment]
> * [ ]  완성 Polygons에 point추가 기능이 사라져 Polygons수정시 불편함이 있음

`Edit Polygons` 모드로 polygons 수정 진행 시 점과 점 사이에 라인을 클릭하면 클릭 위치에 점이 추가되는 것을 확인했습니다.

**Comment by HunJ93** [comment]
이미지 변환시 하기와 같은 오류가 지속적으로 발생함. 일부 라벨러의 경우 오류가 발생하더라도 이미지 50장 전체가 변환이 된다고 하나 몇몇 라벨러들의 경우 전체 50장의 이미지가 변환되지 않는다고 함
![image](https://user-images.githubusercontent.com/100122356/168706320-6f7e7178-5a13-4629-9aef-63a8fa0f956f.png)

**Comment by eungiCho** [comment]
> 이미지 변환시 하기와 같은 오류가 지속적으로 발생함. 일부 라벨러의 경우 오류가 발생하더라도 이미지 50장 전체가 변환이 된다고 하나 몇몇 라벨러들의 경우 전체 50장의 이미지가 변환되지 않는다고 함

https://github.com/ROBOTIS-move/labelme/issues/4#issuecomment-1127109391 과 동일한 문제로 파악됩니다. 이 부분은 해결 완료되었던 문제로 라벨미 재설치 안내드렸습니다.

**Comment by eungiCho** [comment]
- [ ] `ctrl+j 누르고 라벨링 되어있는 점이없는 선부분 누르니까 자꾸 새로운 점이 생성되는데 해제하는 방법 없나요`
점을 생성하는 기능을 껐다 켰다 할 수 있는 기능 필요 (현재는 `edit mode`에서 엣지를 클릭하면 항상 새로운 점이 생성 됨)

**Comment by eungiCho** [comment]
이번 이슈는 여기에서 마무리하겠습니다.
이후에 발생하는 `labelme 사용 중 문제`는 문제별로 각각의 이슈를 생성해주세요.
