### ISSUE TITLE
Detection labeling을 위한 기능 추가 요청

### ISSUE THREAD

**Issue by jongsuff** [ROBOTIS-move/labelme#54]
다음과 같이 detection labeling 관련 단축키와 기능이 추가되었으면 합니다~!
- 박스 삭제 시 팝업창 띄우지 않는 기능 추가 (유무 선택)
- 단축키로 박스 우하단 포인트 이동 (2pixel)
  - 1: Up
  - 2: Down
  - 3: Left
  - 4: Right
- 클래스 변경창 단축키 추가 (박스 클릭 후 `E`버튼으로 클래스 변경 창 팝업)

**Comment by eungiCho** [comment]
`feature-detection-labeling`에 작업해두었습니다. 기능 확인 부탁드립니다~!
