### ISSUE TITLE
이미지 끝에 점이 같은 곳에 여러 개 찍혀있을 때 점이 정상적으로 찍히지 않는 문제

### ISSUE THREAD

**Issue by HunJ93** [ROBOTIS-move/labelme#62]
1. 
![이슈 1](https://user-images.githubusercontent.com/100122356/203201025-0166ab0f-89c1-4603-b547-8eedeb7704e3.png)
- 위 사진 좌측처럼 이미지 끝에서 한 곳에 점이 여러개 찍혀 있는 상황입니다.

2. 
![이슈 2](https://user-images.githubusercontent.com/100122356/203201035-7a07bf47-c410-4d22-8c5d-54620195d636.png)
- 1번의 상황에서 점을 추가하기 위해 Ctrl + B로 점 추가 기능을 On후 다른 곳을 클릭하면 점이 클릭한 곳에 찍혀 해당 Segmentation과 이어져 선처럼 나오게 됩니다.

3. 
![이슈 3](https://user-images.githubusercontent.com/100122356/203201037-97dada06-c29d-4795-80ff-82c1dd0c0edf.png)
- 이미지 밖에는 점이 찍히지 않아야 하지만 해당 버그가 있을 때는 이미지 밖에도 점이 찍힙니다.

**Comment by jongsuff** [comment]
해당 이슈는 #69 에서 해결했으므로 닫겠습니다~!
