### ISSUE TITLE
비정상적 json 파일 생성

### ISSUE THREAD

**Issue by MilyangParkJaeHun** [ROBOTIS-move/labelme#64]
- 라벨링 검토 완료까지 된 데이터 중 아래와 같은 비정상적인 json 파일이 생성되는 문제점을 발견하였습니다.
- classType에 null 값이 들어가고 그 이후 값들도 채워지지 않고 있습니다.

- 정상적 json file
``` 
  "imagePath": "1666832931346455467.jpg",
  "imageData": null,
  "imageHeight": 360,
  "imageWidth": 640,
  "classType": "outdoor_segmentation",
  "grids": [],
  "lineColor": [
    0,
    255,
    0,
    128
  ],
  "fillColor": [
    255,
    0,
    0,
    128
  ]
}
```
- 비정상적  json file
```
  "imagePath": "1666832931346455467.jpg",
  "imageData": null,
  "imageHeight": 360,
  "imageWidth": 640,
  "classType": null
}
```

**Comment by MilyangParkJaeHun** [comment]
@HunJ93 님 위와 같은 사례로 문의 들어온 적 있었던거 같은데
위와 같은 json 파일도 labelme에서 검토할 때 문제없이 열어지고 있는지 궁금합니다

**Comment by HunJ93** [comment]
@MilyangParkJaeHun 
해당 사례로 인해 문제가 있었던 적이 있습니다.
오류 JSON파일의 경우 변환이 되지 않아 변환 파일에서 빠지는 일이 있었습니다. 따라서 검토도 되지 않았습니다.
변환 후 masked, overlayed 폴더의 파일 개수를 일일이 모두 확인해보지 않아 얼마나 빈번히 발생하는지 알 수는 없으나 오류 JSON파일의 경우 검토가 되지 않았다고 판단하시면 됩니다.

**Comment by jongsuff** [comment]
해당 이슈는 작업도중 Delete file버튼을 클릭하고 다시 작업을 하는 경우 json파일 내에 'classType'이 Null값으로 저장되면서 생기는 문제인것 같습니다.
작업 규칙상 라벨링 전에 json파일을 미리 생성하고 이때 'classType'을 지정하는데, Delete file을 누른 시점으로부터는 현재 작업중인 클래스를 알 수 없기 때문에 원래의 'classType'을 복구시키기 어려운 점이 있습니다.
라벨러분들이 작업을 하는 도중 Delete file을 의도적으로 누르실 일은 없다고 판단하여 #65에서 해당 버튼을 비활성화 하는 방식으로 대응하도록 하겠습니다.
