### ISSUE TITLE
변환 pop up창에 이미지 파일 이름 추가

### ISSUE THREAD

**Issue by HunJ93** [ROBOTIS-move/labelme#74]
검토 시 변환 pop up창에 masked_image와 overlayed_image 이름만 뜨는게 아닌 현재 보고 있는 파일 이름도 뜰 수 있도록 수정 부탁드리겠습니다.
"before"
![before](https://user-images.githubusercontent.com/100122356/226255485-d1e43b32-4a24-44dc-bbc9-b425b536a55e.png)

"after"
![after](https://user-images.githubusercontent.com/100122356/226255488-cd05ca2b-436c-4a79-b72d-021a9b7215a3.png)

**Comment by jongsuff** [comment]
다음 스프린트에 반영하도록 하겠습니당

**Comment by jongsuff** [comment]
해당 이슈는 #77 에서 대응 완료하여 이슈 닫겠습니다!
